# -*- coding: utf-8 -*-
"""
MDS-Onto controlled property vocabulary — the single source for every
relationship/attribute predicate the pipeline emits (Getting Started §7.2:
"every relationship should be one of these").

Two-pass resolution (see docs/PROCESS.md):
  Pass 1  resolve_data_property() / resolve_object_property()  — deterministic
          (exact / token / fuzzy match), no LLM, no network.
  Pass 2  llm_choose()  — for the unmatched tail only: shortlist the top-N
          canonical candidates and let the LLM pick FROM that list (or 'none').

The registry is parsed from data/mds_onto_properties.md (one line per term:
``* [Label](...index-en.html#<FULL_IRI>)``), grouped into object / data /
annotation properties. Import-light: stdlib only; the LLM step lazy-imports.
"""
from __future__ import annotations

import os
import re
import json
import functools
from difflib import SequenceMatcher

_REGISTRY_MD = os.getenv(
    "MDS_PROPERTIES_FILE",
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "mds_onto_properties.md"),
)

# IRI prefix -> curie label (for display / optional prefixed output).
_PREFIXES = (
    ("https://cwrusdle.bitbucket.io/mds/", "mds"),
    ("https://www.commoncoreontologies.org/", "cco"),
    ("http://purl.obolibrary.org/obo/BFO_", "bfo"),
    ("http://purl.obolibrary.org/obo/IAO_", "iao"),
    ("http://www.w3.org/2004/02/skos/core#", "skos"),
    ("http://qudt.org/schema/qudt/", "qudt"),
    ("http://purl.org/dc/terms/", "dcterms"),
    ("http://purl.org/dc/elements/1.1/", "dc"),
)

# Leading verb stems stripped from a property label to get its "core" subject
# (so "has Voltage" -> "voltage" matches the concept "open circuit voltage").
_VERB_PREFIX = re.compile(r"^(has|is|are|contains|uses|use|delivers|holds|"
                          r"generated by|generated|produced by|produced|launched|"
                          r"mounted|acquired|owned by|processed)\b", re.I)
_STOP = {"of", "the", "a", "an", "and", "or", "to", "in", "on", "by", "with",
         "per", "for", "as", "at", "from"}
_CAMEL = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def _curie(iri: str) -> str:
    for base, pref in _PREFIXES:
        if iri.startswith(base):
            return f"{pref}:{iri[len(base):]}"
    return iri


def _local(iri: str) -> str:
    return re.split(r"[#/]", iri.rstrip("#/"))[-1]


def _words(text: str) -> list[str]:
    text = _CAMEL.sub(" ", str(text or ""))
    text = re.sub(r"[^a-z0-9 ]", " ", text.lower())
    return [w for w in text.split() if w and w not in _STOP]


def _core_tokens(label: str, local: str) -> frozenset:
    """Subject tokens of a property (verb stem removed), from label + IRI local."""
    base = _VERB_PREFIX.sub("", label).strip() or label
    toks = set(_words(base))
    # IRI local name often carries the cleanest signal (e.g. hasElectronicBandGap).
    loc = _VERB_PREFIX.sub("", " ".join(_words(local))).strip()
    toks |= set(loc.split())
    return frozenset(t for t in toks if t not in _STOP)


@functools.lru_cache(maxsize=1)
def load() -> dict:
    """Parse the registry markdown -> {'object':[...], 'data':[...], 'annotation':[...]}.
    Each entry: {label, iri, curie, local, tokens(frozenset), phrase(str)}."""
    out: dict[str, list] = {"object": [], "data": [], "annotation": []}
    section = None
    line_re = re.compile(r"^\*\s*\[(?P<label>[^\]]+)\]\([^#]*#(?P<iri>\S+)\)")
    try:
        with open(_REGISTRY_MD, encoding="utf-8") as fh:
            for raw in fh:
                low = raw.strip().lower()
                if low.startswith("## object"):
                    section = "object"; continue
                if low.startswith("## data"):
                    section = "data"; continue
                if low.startswith("## annotation"):
                    section = "annotation"; continue
                m = line_re.match(raw.strip())
                if not m or section is None:
                    continue
                label = m.group("label").strip()
                iri = m.group("iri").strip()
                local = _local(iri)
                phrase = " ".join(_words(_VERB_PREFIX.sub("", label).strip() or label))
                out[section].append({
                    "label": label, "iri": iri, "curie": _curie(iri), "local": local,
                    "tokens": _core_tokens(label, local), "phrase": phrase,
                })
    except FileNotFoundError:
        pass
    return out


def _score(name_tokens: set, name_text: str, entry: dict) -> float:
    """Match score in [0,1] of a concept/predicate name against a property entry.
    `name_text` must preserve word order so phrase containment is meaningful."""
    etoks = entry["tokens"]
    phrase = entry["phrase"]
    if not etoks or not name_tokens:
        return 0.0
    ntok = len(name_tokens)
    ptok = len(phrase.split()) if phrase else 0
    # Strong: the property's core phrase appears verbatim in the name. Reward how
    # much of the NAME the phrase covers so a specific multi-word property
    # ("material composition") beats a generic one-word property ("material").
    if phrase and phrase in name_text:
        return min(0.99, 0.80 + 0.19 * (ptok / max(ntok, 1)))
    # The name is a subset of a longer property phrase (weaker, still a hit).
    if phrase and name_text in phrase:
        return 0.80
    # Token coverage (no order): blend property-side and name-side coverage.
    inter = len(etoks & name_tokens)
    prop_cov = inter / len(etoks)
    name_cov = inter / ntok
    overlap = 0.55 * prop_cov + 0.45 * name_cov
    # Fuzzy only counts as a near-miss catcher above a high bar (avoids
    # "fill factor" ~ "file format" false positives).
    fuzzy = SequenceMatcher(None, phrase, name_text).ratio()
    return max(overlap, fuzzy if fuzzy >= 0.85 else 0.0)


def _entries(kind: str) -> list:
    """Entries for a kind. 'attr' = object + data (an attribute like 'open circuit
    voltage' maps to mds:hasVoltage, which MDS-Onto models as an OBJECT property)."""
    reg = load()
    if kind == "attr":
        return reg["object"] + reg["data"]
    return reg.get(kind, [])


def _resolve(name: str, kind: str, threshold: float) -> dict | None:
    entries = _entries(kind)
    words = _words(name)
    nt = set(words)
    ntext = " ".join(words)        # ordered, so phrase containment is meaningful
    best, best_s = None, 0.0
    for e in entries:
        s = _score(nt, ntext, e)
        # On ties prefer the more SPECIFIC property (more core tokens).
        if s > best_s or (s == best_s and best and len(e["tokens"]) > len(best["tokens"])):
            best, best_s = e, s
    if best and best_s >= threshold:
        return {"iri": best["iri"], "curie": best["curie"], "label": best["label"],
                "score": round(best_s, 3)}
    return None


def resolve_attribute_property(name: str, threshold: float = 0.82) -> dict | None:
    """Best canonical property (object OR data) for a concept/attribute name.
    Attributes like 'open circuit voltage' map to mds:hasVoltage (an object
    property under MDS-Onto's BFO quality pattern), so both kinds are searched."""
    return _resolve(name, "attr", threshold)


def resolve_data_property(name: str, threshold: float = 0.62) -> dict | None:
    """Best canonical DATA property for a concept/attribute name, or None."""
    return _resolve(name, "data", threshold)


def resolve_object_property(name: str, threshold: float = 0.6) -> dict | None:
    """Best canonical OBJECT property for a relationship phrase/predicate, or None."""
    return _resolve(name, "object", threshold)


def shortlist(name: str, kind: str = "attr", n: int = 15) -> list[dict]:
    """Top-N canonical candidates (for the LLM fallback to choose from)."""
    entries = _entries(kind)
    words = _words(name); nt = set(words); ntext = " ".join(words)
    scored = sorted(((_score(nt, ntext, e), e) for e in entries),
                    key=lambda x: x[0], reverse=True)
    return [{"iri": e["iri"], "curie": e["curie"], "label": e["label"], "score": round(s, 3)}
            for s, e in scored[:n] if s > 0]


def annotation_iri(name: str) -> str | None:
    """Full IRI of an annotation property by (loose) name, e.g. 'definition'."""
    key = "".join(_words(name))
    for e in load().get("annotation", []):
        if "".join(_words(e["label"])) == key or e["local"].lower() == name.lower():
            return e["iri"]
    return None


def llm_choose(name: str, kind: str = "data", n: int = 15, domain_hint: str = "") -> dict | None:
    """Pass 2: deterministic first; if no confident match, let the LLM pick from a
    shortlist of canonical candidates (never inventing a predicate). Returns the
    chosen entry or None (caller falls back to mint/generic). Degrades to the
    deterministic result if the LLM is unavailable."""
    det = _resolve(name, kind, 0.62 if kind == "data" else 0.6)
    if det:
        return det
    cands = shortlist(name, kind, n)
    if not cands:
        return None
    try:
        from pydantic import BaseModel, Field
        from pydantic_ai import Agent
        from kw import llm
        from kw.config import pydantic_model, output_spec

        class _Pick(BaseModel):
            iri: str = Field(description="the chosen property IRI exactly as listed, or 'none'")

        menu = "\n".join(f"- {c['label']}  ->  {c['iri']}" for c in cands)
        agent = Agent(pydantic_model, output_type=output_spec(_Pick), retries=2,
                      system_prompt=("You map a scientific term to the single best-fitting "
                                     f"MDS-Onto {kind} property. Domain: {domain_hint or 'materials science'}. "
                                     "Choose ONLY from the provided list; if none fits, return 'none'."))
        res = llm.run_sync(agent, f"Term: {name}\nCandidates:\n{menu}")
        choice = (res.output.iri or "").strip()
        for c in cands:
            if choice == c["iri"]:
                return c
        return None
    except Exception as exc:                                   # noqa: BLE001
        print(f"  [mds_props] LLM property pick skipped ({type(exc).__name__})")
        return None


def build_json(out_path: str | None = None) -> str:
    """Dump the parsed registry to data/mds_properties.json (for inspection)."""
    reg = load()
    serial = {k: [{kk: (sorted(vv) if isinstance(vv, frozenset) else vv)
                   for kk, vv in e.items()} for e in lst] for k, lst in reg.items()}
    out_path = out_path or os.path.join(os.path.dirname(_REGISTRY_MD), "mds_properties.json")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(serial, fh, indent=2)
    return out_path
